name: release

on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"
      - name: Release Go module
        run: |
          go mod tidy
          GOPROXY=proxy.golang.org go list -m github.com/neurocode-io/go-pkgs@${{  github.ref_name }}
